import random
import math

def problem001():
    print("-------------------------------------------------------------------------------------------------")
    print("\nIf we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. \nThe sum of these multiples is 23.")
    print("Find the sum of all the multiples of 3 or 5 below 1000.\n")
    print("-------------------------------------------------------------------------------------------------")
    sum = 0
    for i in range(1000):
        if(i % 3 == 0 or i % 5 == 0):
            sum += i
    return sum

def problem002():
    print("-------------------------------------------------------------------------------------------------")
    print("\nEach new term in the Fibonacci sequence is generated by adding the previous two terms. \nBy starting with 1 and 2, the first 10 terms will be: ")
    print("1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...")
    print("\n-------------------------------------------------------------------------------------------------")


def problem003(number):
    print("Hello", number)

def problem004(number):
    print("Hello", number)

def problem005(number):
    print("Hello", number)

def problem006(number):
    print("Hello", number)